# Device tree
DEVICE_PATH := device/xiaomi/dali

# Architecture
TARGET_ARCH := arm64
TARGET_ARCH_VARIANT := armv9-a
TARGET_CPU_ABI := arm64-v8a
TARGET_CPU_VARIANT := generic

# Platform
TARGET_BOARD_PLATFORM := mt6991
TARGET_BOOTLOADER_BOARD_NAME := mt6991
TARGET_NO_BOOTLOADER := true
TARGET_COPY_OUT_VENDOR := vendor
TARGET_COPY_OUT_ODM := odm

# Vendor boot
BUILD_BROKEN_ELF_PREBUILT_PRODUCT_COPY_FILES := true
BOARD_KERNEL_BASE := 0x00000000
BOARD_KERNEL_PAGESIZE := 4096
BOARD_MKBOOTIMG_ARGS += --header_version 4 --kernel_offset 0x80000000 --ramdisk_offset 0xa6f00000
BOARD_MKBOOTIMG_ARGS += --tags_offset 0x87c80000 --dtb_offset 0x87c80000 --board ""
BOARD_INCLUDE_DTB_IN_BOOTIMG := true
BOARD_PREBUILT_DTBIMAGE_DIR := $(DEVICE_PATH)/prebuilt/dtb
BOARD_VENDOR_BOOTIMAGE_PARTITION_SIZE := 67108864
BOARD_FLASH_BLOCK_SIZE := 262144
TARGET_NO_KERNEL := true
TARGET_NO_RECOVERY := true
BOARD_USES_GENERIC_KERNEL_IMAGE := true
BOARD_BOOT_HEADER_VERSION := 4
BOARD_AVB_ENABLE := true

# Filesystems
TARGET_USERIMAGES_USE_EXT4 := true
TARGET_USERIMAGES_USE_F2FS := true
BOARD_ODMIMAGE_FILE_SYSTEM_TYPE := ext4

# Recovery
TW_BRIGHTNESS_PATH := "/sys/class/leds/lcd-backlight/brightness"
TW_MAX_BRIGHTNESS := 16383
TW_SUPPORT_INPUT_AIDL_HAPTICS := true
TW_SUPPORT_INPUT_AIDL_HAPTICS_FQNAME := "IVibrator/vibratorfeature"
TW_THEME := portrait_hdpi
TW_EXCLUDE_DEFAULT_USB_INIT := true
TW_INCLUDE_FASTBOOTD := true

# Encryption
TW_INCLUDE_CRYPTO := true
TW_INCLUDE_CRYPTO_FBE := true
TW_INCLUDE_OMAPI := true
TW_USE_FSCRYPT_POLICY := 2
TW_USE_DMCTL := true

# Version
PLATFORM_VERSION := 99.87.36
PLATFORM_VERSION_LAST_STABLE := $(PLATFORM_VERSION)
PLATFORM_SECURITY_PATCH := 2099-12-31
VENDOR_SECURITY_PATCH := $(PLATFORM_SECURITY_PATCH)
BOOT_SECURITY_PATCH := $(PLATFORM_SECURITY_PATCH)

# Properties
TW_INCLUDE_RESETPROP := true
TW_INCLUDE_LIBRESETPROP := true

# Storage
BOARD_USES_METADATA_PARTITION := true
RECOVERY_SDCARD_ON_DATA := true
TW_SKIP_ADDITIONAL_FSTAB := true

# Logging
TWRP_INCLUDE_LOGCAT := true
TARGET_USES_LOGD := true

# Device
TARGET_RECOVERY_DEVICE_DIRS := $(DEVICE_PATH)
TARGET_RECOVERY_FSTAB := $(DEVICE_PATH)/recovery.fstab

# Storage
BOARD_HAS_NO_REAL_SDCARD=true

# GLUTTONY
TW_EXCLUDE_APEX := true
TW_EXTRA_LANGUAGES := true

BOARD_RAMDISK_USE_LZ4 := false
BOARD_MOVE_RECOVERY_RESOURCES_TO_VENDOR_BOOT := true
BOARD_INCLUDE_RECOVERY_RAMDISK_IN_VENDOR_BOOT := true

TW_ENABLE_ALL_PARTITION_TOOLS := true
TW_INCLUDE_NTFS_3G := true

TW_RECOVERY_ADDITIONAL_RELINK_LIBRARY_FILES += \
    $(TARGET_OUT_SHARED_LIBRARIES)/libfs_mgr_binder.so \
    $(TARGET_OUT_SHARED_LIBRARIES)/libsnapshot.so

# Device-specific configuration
# SPDX-License-Identifier: Apache-2.0

BOARD_KERNEL_CMDLINE := bootopt=64S3,32N2,64N2 erofs.reserved_pages=64

TARGET_RECOVERY_PIXEL_FORMAT := RGBX_8888
TW_DEFAULT_BRIGHTNESS := 2270
TW_CUSTOM_BATTERY_PATH := "/sys/class/power_supply/battery"
TARGET_OTA_ASSERT_DEVICE := dali
TW_DEVICE_VERSION := dali
